### ISSUE TITLE
Cannot build app

### ISSUE THREAD

**Issue by kortenkamp** [MathCityMap/O1-MCM-mobile-App#36]
The readme says you should run `yarn` first. Doing so does throw the following error for me (on macOS):

```
$ yarn
yarn install v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["esprima-fb@~3001.0001.0000-dev-harmony-fb"] is trying to unpack in the same destination "/Users/ulli/Library/Caches/Yarn/v2/npm-esprima-fb-3001.1.0-dev-harmony-fb-b77d37abcd38ea0b77426bb8bc2922ce6b426411" as pattern ["esprima-fb@~3001.1.0-dev-harmony-fb"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > ionic-angular@3.8.0" has incorrect peer dependency "rxjs@5.4.3".
warning " > ngx-youtube-player@0.1.0" has incorrect peer dependency "@angular/common@>= 5.0.0".
warning " > ngx-youtube-player@0.1.0" has incorrect peer dependency "@angular/core@>= 5.0.0".
[4/4] 📃  Building fresh packages...
[1/4] ⡀ node-expat
[2/4] ⡀ fsevents
[3/4] ⡀ node-sass
error /Users/ulli/O1-MCM-mobile-App/node_modules/node-expat: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/ulli/O1-MCM-mobile-App/node_modules/node-expat
Output:
module.js:538
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/tracker-stream.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)


```

**Comment by am-immanuel** [comment]
Hi there, sorry for late reply. Did you meanwhile succeed? If not, I'll be glad to support you.

**Comment by kortenkamp** [comment]
Thanks, it works now (after pulling the latest version). Now I just have to figure out whether or how I can run this on the iOS simulator (I don't have ionic).
